//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        public int id { get; set; }
        public string m_name { get; set; }
        public int age_res { get; set; }
        public double rating { get; set; }
        public string category { get; set; }
        public string lang { get; set; }
    }
}
