//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int ID { get; set; }
        [Required(ErrorMessage="Enter your username")]
        public string username { get; set; }
        [Required(ErrorMessage = "Enter your passowrd")]
        [DataType(DataType.Password)]
        public int password { get; set; }
        [Required(ErrorMessage = "Enter your age")]
        public int age { get; set; }
        public Nullable<bool> have_credit_card { get; set; }
        public Nullable<int> credit_card_number { get; set; }
        public Nullable<short> ccv { get; set; }
        [Required(ErrorMessage = "Enter your national ID number")]
        public int national_ID { get; set; }
    }
}
